---
title: "Research vision for the Copernicus Institute"
author: "Dr. Felipe Melo"
date: "11/01/2022"
output: html_document
   
---

## **Goals and Philosophy**
My research strategy is focused on the study of the ecology and management of social-ecological landscapes. To achieve this, I pursue to establish an interdisciplinary research group built on partnerships across many disciplines such as landscape ecology, functional ecology, ecological restoration and political ecology. My research vision for the next three years is to consolidate a world-class research group on the study of coupled social and ecological systems, delivering high impact contributions to both science and to the resolution of real-world problems of biodiversity conservation and the improvement of human livelihoods. 

To achieve these goals I draw on the social-ecological systems framework and tools to address the interlinkages between biodiversity and human activities in novel landscapes. Therefore, I am interested in all kinds of interactions between human activities and biodiversity that happens in working landscapes created by humans such as rangelands and fragmented forest landscapes. Natural resources use, biological invasion, changes in community assembly pattern and processes as well as ecological restoration and conservation policies are among my main research interests. 
I am trained in natural sciences, specifically in ecology but my interests towards interdisciplinary research that have always been intense, has increased in the last few years. I am very interested in conducting research with a strong ecological ground and clear management application aiming at the sustainability of tropical human-modified landscapes.

## **Historic of contributions to science **

Many of my colleagues credit me as having a sharp critical thinking that takes me beyond my comfort zone when doing science. Early in my career I experienced writing reviews and perspective papers in leading journals such as Biological Conservation and Trends in Ecology and Evolution. My innovative ideas on social-ecological systems are expressed on pieces that discuss: The role of human-modified landscapes in maintaining biodiversity (Melo et al 2013); How proliferation of disturbance-adapted species cause biotic homogenization (Tabarelli et al 2012); How to scale-up long lasting restoration projects (Melo et al 2013b); Assessing alternative successional pathways in Tropical forests (Arroyo-Rodríguez et al. 2017) and recently, introducing the novel concept of “forest security” as a fourth dimension for the water, energy and food security nexus (Melo et al 2021). I have also contributed to many other cutting edge ideas and scientific debates on themes related to landscape ecology such as the debate around whether forest fragmentation is good or bad to biodiversity. I consider that I am able to constantly think on new and integrative ideas that address how human-made landscapes can (or cannot) maintain both biodiversity and human livelihoods. 

I have a strong publication record with a vast network of collaborators from many countries. In Brazil, where I am based, I am part of the scientific committee of the Brazilian Platform for Biodiversity and Ecosystem Services (the Brazilian chapter of the IPBES) and I am part of the public policy workgroup of the Brazilian Association of Ecologists (ABECO). I am currently leading a research team working simultaneously on two multi-institutional projects funded by the Brazilian National Council for Research Development (CNPq). I have co-organized three symposiums in international meetings (SER 2011; ATBC 2013 and 2017). In 2014 I first-authored a paper that called for the action to conserve the three-banded armadillo and its habitat, the Brazilian dry forest, after this animal was chosen as the official mascot of the 2014 FIFA World Cup. This resulted in a huge campaign and media coverage that ended up with the creation of a 110,000 hectares protected area after my personal participation in political negotiation and the elaboration of supporting studies for the creation of this protected area. This story of success in conservation is taught in a second paper (Bernard and Melo 2019) and in a video (see here). 


## **Research vision, future plans and networking **

My research strategy aims to delve deeper into the ecology and management of human-dominated landscapes. I foresee plenty of opportunities to apply for and get grants from varying external and US sources such as National Science Foundation - NSF and diverse international funds from private institutions and NGOs. My past research income records are solid and provided a constant flux of economic resources for funding my research. My plan in Cornell for the next few years is to build a dedicated research group on ecology and management of social-ecological landscapes. My links with Brazilian and Mexican institutions allow the establishment of large research programs based on Latin America with access to funds from these countries in cooperation with a network of collaborators. I have developed a broad and productive network of strong scientific collaborations with researchers from institutions in the UK (e.g. co-supervising PhD students, project co-management and previous sabbatical visit to Lancaster University with Dr. Luke Parry), USA (e.g. CO-I on PARTNERS project with Dr. Robin Chazdon at University of Connecticut), Mexico (e.g. co-running postgraduate field courses in Mexico and Brazil with Dr. Victor Arroyo-Rodríguez, UNAM). This is reflected in my publishing record of co-authored papers in journals including PNAS, Biological Reviews and Ecology Letters. 

I am now coordinating two simultaneous projects funded by the Brazilian Council for Research Development (CNPq) that covers many aspects of the aims and objectives of this job advertisement. These projects involve both undergraduate and graduate students, financial support for field trips and consultancy contracts to compile, manage and analyze databases on forest cover and social-economic indicators of a region composed of nine states where more than 26 million people inhabit. I want to highlight the project entitled “Effects of climate change on forest security of the Caatinga ecosystem in Brazil”. This project fits perfectly with the goals of the Cornell Atkinson Center for Sustainability and UN Sustainable Development Goals. This project aims to understand human dependency on forest services and goods as well as rights of access to these services for local, traditional communities. Therefore, this is a great opportunity to move to Cornell with an ongoing and financed project that would help me to establish prompt collaborations with the staff of the Department of Natural Resources and the Environment at Cornell University. 

Finally, I believe that natural and social sciences have been wrongly and unfortunately understood as separate fields of knowledge. My research vision is to contribute to construct effective bridges between these two sciences through a world-class research program that I would like to develop in the vibrant environment of the University of Cornell.
