---
title: "Research vision for the CREAF"
author: "Dr. Felipe Melo"
date: "18/07/2021"
output:
  html_document:
    df_print: paged
---

## **Goals and Philosophy**

My research strategy is focused on the study of the ecology and management of social-ecological landscapes. I pursue to establish an interdisciplinary research group built on partnerships across many disciplines such as landscape ecology, functional ecology, ecological restoration and political ecology. My research vision for the next three years is to consolidate a world-class research group on the study of coupled social and ecological systems, delivering high impact contributions to both science and to the resolution of real-world problems of biodiversity conservation and the improvement of human livelihoods. 

To achieve these goals I draw both on ecology and on the social-ecological systems framework to address the interlinkages between biodiversity and human activities in novel landscapes. Therefore, I am interested in all kinds of interactions between human activities and biodiversity that take place in working landscapes created by humans. Natural resources use, biological invasion, changes in community assembly pattern and processes as well as ecological restoration and conservation policies are among my main research interests.

I am trained in natural sciences, specifically in plant ecology but, my interests towards interdisciplinary research have always been intense. I am very interested in conducting research with a strong ecological ground and clear management application aiming at the sustainability of social-ecological landscapes.


## **Historic of contributions to science **

Many of my colleagues credit me as having a sharp critical thinking that takes me beyond my comfort zone when doing science. Early in my career I experienced writing reviews and perspective papers where I could share somo of my reflections on the ecology and management of altered forest ecosystems. My innovative ideas on social-ecological systems are expressed on pieces that discuss: The role of human-modified landscapes in maintaining biodiversity [(Melo et al 2013)](https://www.sciencedirect.com/science/article/pii/S0169534713000037); How proliferation of disturbance-adapted species cause biotic homogenization [(Tabarelli et al 2012)](https://www.sciencedirect.com/science/article/pii/S0006320712002893?via%3Dihub); How to scale-up long lasting restoration projects [(Melo et al 2013b)](https://www.sciencedirect.com/science/article/pii/S1462901113001494); Assessing alternative successional pathways in Tropical forests [(Arroyo-Rodríguez et al. 2017)](https://onlinelibrary.wiley.com/doi/10.1111/brv.12231) and recently, introducing the novel concept of “forest security” as a fourth dimension for the water, energy and food security nexus [(Melo et al 2021)](https://www.nature.com/articles/s41893-020-00608-z). I have also contributed to many other cutting edge ideas and scientific debates on themes related to landscape ecology such as the debate around whether forest fragmentation is [good](https://doi.org/10.1016/j.biocon.2018.12.026) or [bad](https://doi.org/10.1016/j.biocon.2018.07.022) to biodiversity. I consider that I am able to constantly think on new and integrative ideas that address how human-made landscapes can (or cannot) maintain both biodiversity and human livelihoods. I have a strong publication record in leading journals with a broad network of collaborators from many countries.

My contributions to society goes beyond the academic wolrd. In Brazil, where I am based, I am part of the [scientific committee of the Brazilian Platform for Biodiversity and Ecosystem Services](https://www.bpbes.net.br/quem-somos/biografias/) (the Brazilian chapter of the IPBES) and I am part of the public policy workgroup of the Brazilian Association of Ecologists (ABECO). I am currently leading a research team working simultaneously on two multi-institutional projects funded by the Brazilian National Council for Research Development (CNPq). I have co-organized three symposiums in international meetings (SER 2011; ATBC 2013 and 2017). [In 2014 I first-authored a paper](https://onlinelibrary.wiley.com/doi/abs/10.1111/btp.12114) that called for the action to conserve the three-banded armadillo and its habitat, the Brazilian dry forest, after this animal was chosen as the official mascot of the 2014 FIFA World Cup. This resulted in a [huge campaign](https://www.change.org/p/brazilian-minister-of-the-environment-izabella-teixeira-for-the-brazilian-government-to-create-a-natural-reserve-for-the-armadillo/dashboard?source_location=user_profile_started) and [media coverage](https://www.theguardian.com/science/animal-magic/2014/jun/09/fifa-brazil-failing-threatened-armadillo-conservation#:~:text=In%202012%2C%20Fifa%20unveiled%20its,a%20colourful%20armadillo%20called%20Fuleco.) that ended up with the creation of a 110,000 hectares protected area after my personal participation in political negotiation and the elaboration of supporting studies for the creation of this protected area. This story of success in conservation is taught in a [second paper](https://onlinelibrary.wiley.com/doi/abs/10.1111/btp.12681) and in a [videO](https://www.youtube.com/watch?v=rQHAgyrXims). 


## **Research vision, future plans and networking **

My plan at the CREAF, for the next three years, is to build a dedicated research group on ecology and management of social-ecological landscapes. Joining the CREAF staff of researchers is a singular opportunity to establish productive scientific partnerships with its highly regarded team of scientists The CREAF expertises cover several of my research interests under all main research areas of: Global Change, Biodiversity, Earth Observation and Ecosystem Functioning. Furthermore, I see my research program contributing to many of the six cross-cutting topics such as Forests, Ecosystem Services, Sustainability and Citizen Science, for example. 

I can contribute readily to the CREAF portfolio of research grants as I am now coordinating two simultaneous projects (until December 2023) funded by the Brazilian Council for Research Development (CNPq) that fits many research expertise of the CREAF and attend to the desired expertise of candidates for this job advertisement. In a few words, these projects aim to understand the role of climate change, biological invasion and natural resource uses on plant communities, human livelihoods and ecosystem service provision of the Brazilian seasonal tropical dry forests. Additionally, I plan to apply for EU grants such as the ones from [ERC](https://erc.europa.eu/) (e.g. Consolidator Grants) and/or diverse international funds from private institutions and NGOs. 

I follow the research outputs of some CREAF researchers such as Dr. Francisco Lloret Maya and Professor Maurizio Mencuccini and their work on the functional ecology of drought resistance. Impossible not to be excited with the possibility meet in person and, if possible, work with Professor Josep Penuelas, one of the world’s most important ecology scientists. Also, Dr. Joan Pino Vilalta, current CREAF director, runs an interesting research program on landscape ecology, one of my fields of expertise. Many other researchers from other UAB departments such as the ICREA are references for my current and future work.

My actual links with Brazilian and Mexican institutions allow me to expand CREAF research scope and influence to Latin America with access to funds from these countries in cooperation with a network of collaborators. I have developed a broad and productive network with researchers from institutions in the UK (e.g. co-supervising PhD students, project co-management and previous sabbatical visit to Lancaster University with Dr. Luke Parry), USA (e.g. CO-I on PARTNERS project with Dr. Robin Chazdon at University of Connecticut) and Mexico (e.g. co-running postgraduate field courses in Mexico and Brazil with Dr. Victor Arroyo-Rodríguez, UNAM). This is reflected in my publishing record in journals including Nature Sustainability, PNAS, Trends in Ecology and Evolution, Biological Reviews and Ecology Letters. 

Finally, I believe that moving to CREAF represents a great opportunity to expand and redraft my career. My personal research mission is to contribute to construct effective bridges between ecology and society and this fits nicely with CREAF's mission and vision. I look forward to have a chance to establish an innovative and productive research program in the vibrant environment of the **Centre de Recerca Ecològica i d’Aplicacions Forestals - CREAF**.
