---
title: "Teaching philosophy"
author: "Dr. Felipe Melo"
date: "28/06/2021"
output:
  html_document:
    df_print: paged
---

## Teaching Phylosophy


Being a teacher is amongst the most rewarding facets of my career. I am a biologist by training but my motivation for being a biologist was primarily being a teacher. The beginning of my undergraduate studies in biology was primarily focused on secondary-level teaching. With time, I gradually moved my career focus towards research in ecology but never abandoned my interest in teaching science. When my career path became clearly focused on research I started a continuous investment in improving my skills as a mentor and student supervisor. In the following lines I briefly present my teaching philosophy including the main authors and practices that influenced my teaching practice and how I cope with the challenges of teaching ecology in the Global South.

My first paid job as a biology student was a one year contract in a science museum held by the Pernambuco state government in Brazil. The mission of this museum is to serve as a science popularization tool for primary and secondary students. During my contract in this museum I was trained on participatory methods of science teaching that consists mostly of live demonstration of natural phenomena through interactive experiments and conversation. The staff of the museum shared a common view that science teaching is revolutionary only if it challenges and changes the way kids and teenagers face the world. We deeply discussed the role played by science museums in society. We were also very conscious of the challenges of popularizing science in a poor country where many children struggle to achieve basic levels of literacy. Being part of this staff as an assistant teacher was a marvelous experience that cemented my career path as both a teacher and as a researcher. 

Because teaching was always in my plans as a biologist, I decided early to invest in specific pedagogical skills during my undergraduate studies. I was lucky enough to study at the same university that was the home of one of the most regarded philosophers on education, Paulo Freire. His ‘critical pedagogy’ became worldwide famous and his books were translated to hundreds of languages. I then took some courses in the Education Department that allowed me to adopt Freire’s idea of humanistic science education. This means that science literacy must be committed to transform the world. This is one of the foundational principles of my teaching practice to date. This was complemented with an extra course in ‘history of science’ in the Philosophy Department of the same university. That was the time I was introduced to authors such as Karl Popper and Thomas Khun and their contrasting views on the progress of science. I was then able to develop my own perspective of science as a human enterprise, science history, its social role and potential. This is the background of my practice as a science teacher and comprise the milestones of my teaching philosophy.

In practical terms I am very inclined towards active methods of learning. During my Master’s, In 2002, I took part in a 30 days field course in Ecology of the Amazonian Forest offered by the Smithsonian Institution - USA and National Institute of Amazonian Research - Brazil. I was then presented to my favourite learning and teaching experience largely based on “learning by doing” and “problem-based learning” methods. This field course was life changing for me because I realized that doing research was not a matter of geniality, exclusive to a few privileged minds. For 30 days we conducted dozens of small projects, both collective and individual, supervised or not by experienced researchers in ecology from around the world. For each project we had to present results in a public seminar and write reports that passed through a real process of peer review. All this happened in filed stations in the middle of the Amazonian forest and boats across the Negro and Amazon rivers. I was convinced that putting together the philosophical and practical perspectives from critical pedagogy into problem-solving methods could be a good idea. As a result, I have coordinated, co-organized or participated as an invited teacher in nearly 30 field-courses in ecology and conservation across Brazil and Mexico. I therefore had plenty of opportunities to put into practice my teaching skills and philosophy. Evaluation methods were based on the production of real paper that went through formal peer-review process (example), simulated journals (example here) or book chapters organized into volumes (examples here). 